routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Ingredients
    Route::delete('ingredients/destroy', 'IngredientsController@massDestroy')->name('ingredients.massDestroy');
    Route::resource('ingredients', 'IngredientsController');

    // Ingredient Groups
    Route::delete('igroups/destroy', 'IGroupsController@massDestroy')->name('igroups.massDestroy');
    Route::resource('igroups', 'IGroupsController');

    // Nutrients
    Route::delete('nutrients/destroy', 'NutrientsController@massDestroy')->name('nutrients.massDestroy');
    Route::resource('nutrients', 'NutrientsController');

    // Recipes
    Route::delete('recipes/destroy', 'RecipesController@massDestroy')->name('recipes.massDestroy');
    Route::get('recipes/{recipe}/editnutrients', 'RecipesController@editnutrients')->name('recipes.editnutrients');
    Route::get('recipes/{recipe}/editingredients', 'RecipesController@editingredients')->name('recipes.editingredients');
//    Route::post('recipes/updatenutrients', 'RecipesController@updatenutrients')->name('recipes.updatenutrients');
    Route::resource('recipes', 'RecipesController');


    // Packs
    Route::delete('packs/destroy', 'PacksController@massDestroy')->name('packs.massDestroy');
    Route::resource('packs', 'PacksController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Ingredient extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'ingredients';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'igroup_id',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function igroup()
    {
        return $this->belongsTo(IGroup::class)->withDefault() ;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/IngredientsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyIngredientRequest;
use App\Http\Requests\StoreIngredientRequest;
use App\Http\Requests\UpdateIngredientRequest;
use App\Models\Ingredient;
use App\Models\IGroup;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class IngredientsController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('ingredient_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ingredients = Ingredient::all()->sortBy('name', true);

        return view('admin.ingredients.index', compact('ingredients'));
    }

    public function create()
    {
        abort_if(Gate::denies('ingredient_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        // create a list with available ingredient groups
        $igroups = IGroup::all()->pluck('name', 'id');
        return view('admin.ingredients.create',compact('igroups'));
    }

    public function store(StoreIngredientRequest $request)
    {

        // note that foreigner key will be also updated
        $ingredient = Ingredient::create($request->all());

        return redirect()->route('admin.ingredients.index');
    }

    public function edit(Ingredient $ingredient)
    {
        abort_if(Gate::denies('ingredient_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        // create a list with available ingredient groups
        $igroups = IGroup::all()->pluck('name', 'id');
        return view('admin.ingredients.edit', compact('ingredient','igroups'));
    }

    public function update(UpdateIngredientRequest $request, Ingredient $ingredient)
    {
        $ingredient->update($request->all());

        return redirect()->route('admin.ingredients.index');
    }

    public function show(Ingredient $ingredient)
    {
        abort_if(Gate::denies('ingredient_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.ingredients.show', compact('ingredient'));
    }

    public function destroy(Ingredient $ingredient)
    {
        abort_if(Gate::denies('ingredient_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ingredient->delete();

        return back();
    }

    public function massDestroy(MassDestroyIngredientRequest $request)
    {
        Ingredient::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/ingredients/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.ingredient.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.ingredients.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.ingredient.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ingredient.fields.name_helper') }}</span>
            </div>

            <div class="form-group">
                <label for="igroup">{{ trans('cruds.ingredient.fields.igroup') }}</label>

                <select class="form-control select {{ $errors->has('igroup') ? 'is-invalid' : '' }}" name="igroup_id" id="igroup_id">
                    <option value=""> </option>
                    @foreach($igroups as $id => $igroup)
                        <option value="{{ $id }}" {{ in_array($id, old('igroup', [])) ? 'selected' : '' }}>{{ $igroup }}</option>
                    @endforeach
                </select>
                @if($errors->has('igroup'))
                    <div class="invalid-feedback">
                        {{ $errors->first('igroup') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ingredient.fields.igroup_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/ingredients/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.ingredient.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.ingredients.update", [$ingredient->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.ingredient.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $ingredient->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ingredient.fields.name_helper') }}</span>
            </div>

            <div class="form-group">
                <label for="igroup">{{ trans('cruds.ingredient.fields.igroup') }}</label>

                <select class="form-control select {{ $errors->has('igroup') ? 'is-invalid' : '' }}" name="igroup_id" id="igroup_id">
                    <option value=""> </option>
                    @foreach($igroups as $id => $igroup)
                        <option value="{{ $id }}" {{ $id == old('igroup', $ingredient->igroup_id) ? 'selected' : '' }}>{{ $igroup }}</option>
                    @endforeach
                </select>
                @if($errors->has('igroup'))
                    <div class="invalid-feedback">
                        {{ $errors->first('igroup') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.ingredient.fields.igroup_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/ingredients/index.blade.php
@extends('layouts.admin')
@section('content')
@can('ingredient_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.ingredients.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.ingredient.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.ingredient.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Ingredient">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.ingredient.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.ingredient.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.igroup.fields.igroup') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($ingredients as $key => $ingredient)
                        <tr data-entry-id="{{ $ingredient->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $ingredient->id ?? '' }}
                            </td>
                            <td>
                                {{ $ingredient->name ?? '' }}
                            </td>
                            <td>
                                {{ $ingredient->igroup->name ?? '' }}
                            </td>
                            <td>
                                @can('ingredient_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.ingredients.show', $ingredient->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('ingredient_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.ingredients.edit', $ingredient->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('ingredient_delete')
                                    <form action="{{ route('admin.ingredients.destroy', $ingredient->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('ingredient_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.ingredients.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Ingredient:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/ingredients/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.ingredient.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.ingredients.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.ingredient.fields.id') }}
                        </th>
                        <td>
                            {{ $ingredient->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ingredient.fields.name') }}
                        </th>
                        <td>
                            {{ $ingredient->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.ingredient.fields.igroup') }}
                        </th>
                        <td>
                            {{ $ingredient->igroup->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.ingredients.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection