routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Ingredients
    Route::delete('ingredients/destroy', 'IngredientsController@massDestroy')->name('ingredients.massDestroy');
    Route::resource('ingredients', 'IngredientsController');

    // Ingredient Groups
    Route::delete('igroups/destroy', 'IGroupsController@massDestroy')->name('igroups.massDestroy');
    Route::resource('igroups', 'IGroupsController');

    // Nutrients
    Route::delete('nutrients/destroy', 'NutrientsController@massDestroy')->name('nutrients.massDestroy');
    Route::resource('nutrients', 'NutrientsController');

    // Recipes
    Route::delete('recipes/destroy', 'RecipesController@massDestroy')->name('recipes.massDestroy');
    Route::get('recipes/{recipe}/editnutrients', 'RecipesController@editnutrients')->name('recipes.editnutrients');
    Route::get('recipes/{recipe}/editingredients', 'RecipesController@editingredients')->name('recipes.editingredients');
//    Route::post('recipes/updatenutrients', 'RecipesController@updatenutrients')->name('recipes.updatenutrients');
    Route::resource('recipes', 'RecipesController');


    // Packs
    Route::delete('packs/destroy', 'PacksController@massDestroy')->name('packs.massDestroy');
    Route::resource('packs', 'PacksController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/IGroup.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class IGroup extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'igroups';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function ingredients()
    {
        return $this->hasMany(Ingredient::class, 'igroup_id') ;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/IGroupsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Models\IGroup;
use App\Models\Ingredient;

use App\Http\Requests\MassDestroyIGroupRequest;
use App\Http\Requests\StoreIGroupRequest;
use App\Http\Requests\UpdateIGroupRequest;

use Illuminate\Http\Request;
use Gate;
use Symfony\Component\HttpFoundation\Response;


class IGroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(Gate::denies('igroup_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $igroups = IGroup::all();

        return view('admin.igroups.index', compact('igroups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('igroup_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ingredients = Ingredient::all()->pluck('name', 'id');
        return view('admin.igroups.create', compact('ingredients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreIGroupRequest $request)
    {
        $igroup = IGroup::create($request->all());

        if ( isset($request->ingredients) ) {
            foreach ( $request->ingredients as $ingredient ) {
                $i = Ingredient::find($ingredient);
                $i->update(['igroup_id' => $igroup->id]);
            }
        }

        return redirect()->route('admin.igroups.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\GroupIngredient  $groupIngredient
     * @return \Illuminate\Http\Response
     */
    public function show(IGroup $igroup)
    {
        abort_if(Gate::denies('igroup_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        //dd($igroup->ingredients()->get());
        return view('admin.igroups.show', compact('igroup'));
    }

    /**
     *
     */
    public function edit(IGroup $igroup)
    {
        abort_if(Gate::denies('igroup_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $ingredients = Ingredient::all()->pluck('name', 'id');
        $igroup->load('ingredients');

        return view('admin.igroups.edit', compact('igroup','ingredients'));
    }

    /**
     *
     */
    public function update(Request $request, IGroup $igroup)
    {
        $igroup->update($request->all());

        // clean existing relations, if any
        if ( $igroup->ingredients()->exists() )  {
            foreach ( $igroup->ingredients()->get() as $ingredient ) {
                $ingredient->update(['igroup_id' => null]);
            }
        }

        // set new relations, if any
        if ( isset($request->ingredients) ) {
            foreach ( $request->ingredients as $ingredient ) {
                $i = Ingredient::find($ingredient);
                $i->update(['igroup_id' => $igroup->id]);
            }
        }

        return redirect()->route('admin.igroups.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\IGroup  $igroup
     * @return \Illuminate\Http\Response
     */
    public function destroy(IGroup $igroup)
    {
        abort_if(Gate::denies('igroup_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        // before deletinga a ingredient group, we need to clear all ingredient relations if any
        if ( $igroup->ingredients()->exists() )  {
            foreach ( $igroup->ingredients()->get() as $ingredient ) {
                $ingredient->update(['igroup_id' => null]);
            }
        }
        $igroup->delete();

        return back();
    }

    public function massDestroy(MassDestroyIGroupRequest $request)
    {
        IGroup::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/igroups/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.igroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.igroups.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.igroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.igroup.fields.name_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="" for="ingredients">{{ trans('cruds.igroup.fields.ingredients') }}</label>

                <select class="form-control select2 {{ $errors->has('ingredients') ? 'is-invalid' : '' }}" name="ingredients[]" id="ingredients" multiple >
                    @foreach($ingredients as $id => $ingredient)
                        <option value="{{ $id }}" {{ in_array($id, old('ingredients', [])) ? 'selected' : '' }}>{{ $ingredient }}</option>
                    @endforeach
                </select>
                @if($errors->has('ingredients'))
                    <div class="invalid-feedback">
                        {{ $errors->first('ingredients') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.igroup.fields.ingredients_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/igroups/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.igroup.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.igroups.update", [$igroup->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.igroup.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $igroup->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.igroup.fields.name_helper') }}</span>
            </div>

            <div class="form-group">
                <label class="" for="ingredients">{{ trans('cruds.igroup.fields.ingredients') }}</label>

                <select class="form-control select2 {{ $errors->has('ingredients') ? 'is-invalid' : '' }}" name="ingredients[]" id="ingredients" multiple>
                    @foreach($ingredients as $id => $ingredients)
                        <option value="{{ $id }}" {{ (in_array($id, old('ingredients', [])) || $igroup->ingredients->contains($id)) ? 'selected' : '' }}>{{ $ingredients }}</option>
                    @endforeach
                </select>

                @if($errors->has('ingredients'))
                    <div class="invalid-feedback">
                        {{ $errors->first('ingredients') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.igroup.fields.ingredients_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/igroups/index.blade.php
@extends('layouts.admin')
@section('content')
@can('igroup_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.igroups.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.igroup.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.igroup.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-igroup">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.igroup.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.igroup.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($igroups as $key => $igroup)
                        <tr data-entry-id="{{ $igroup->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $igroup->id ?? '' }}
                            </td>
                            <td>
                                {{ $igroup->name ?? '' }}
                            </td>
                            <td>
                                @can('igroup_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.igroups.show', $igroup->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('igroup_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.igroups.edit', $igroup->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('igroup_delete')
                                    <form action="{{ route('admin.igroups.destroy', $igroup->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('igroup_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.igroups.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-igroup:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/igroups/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.igroup.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.igroups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.igroup.fields.id') }}
                        </th>
                        <td>
                            {{ $igroup->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.igroup.fields.name') }}
                        </th>
                        <td>
                            {{ $igroup->name }}
                        </td>
                    </tr>
                    <tr>
                        <td>{{ trans('cruds.igroup.fields.ingredients') }}</td>
                        <td>
                            @foreach ( $igroup->ingredients()->get() as $ingredient )
                                {{$ingredient->name}}@if(!$loop->last), @endif
                            @endforeach
                        </td>
                    </tr>

                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.igroups.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection