routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Ingredients
    Route::delete('ingredients/destroy', 'IngredientsController@massDestroy')->name('ingredients.massDestroy');
    Route::resource('ingredients', 'IngredientsController');

    // Ingredient Groups
    Route::delete('igroups/destroy', 'IGroupsController@massDestroy')->name('igroups.massDestroy');
    Route::resource('igroups', 'IGroupsController');

    // Nutrients
    Route::delete('nutrients/destroy', 'NutrientsController@massDestroy')->name('nutrients.massDestroy');
    Route::resource('nutrients', 'NutrientsController');

    // Recipes
    Route::delete('recipes/destroy', 'RecipesController@massDestroy')->name('recipes.massDestroy');
    Route::get('recipes/{recipe}/editnutrients', 'RecipesController@editnutrients')->name('recipes.editnutrients');
    Route::get('recipes/{recipe}/editingredients', 'RecipesController@editingredients')->name('recipes.editingredients');
//    Route::post('recipes/updatenutrients', 'RecipesController@updatenutrients')->name('recipes.updatenutrients');
    Route::resource('recipes', 'RecipesController');


    // Packs
    Route::delete('packs/destroy', 'PacksController@massDestroy')->name('packs.massDestroy');
    Route::resource('packs', 'PacksController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Pack.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Pack extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'packs';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'fullname',
        'thumbnail',
        'weight',
        'weight_real',
        'ingredients_info',
        'nutritional_info',
        'allergenic_info',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function recipes()
    {
        return $this->belongsToMany(Recipe::class)->withPivot('amount');
    }

    public function ingredients()
    {
        return $this->belongsToMany(Ingredient::class)->withPivot('amount');
    }

    public function nutrients()
    {
        return $this->belongsToMany(Nutrient::class)->withPivot('amount');
    }
}

app/Http/Controllers/Admin/PacksController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPackRequest;
use App\Http\Requests\StorePackRequest;
use App\Http\Requests\UpdatePackRequest;
use App\Models\Recipe;
use App\Models\Ingredient;
use App\Models\IGroup;
use App\Models\Nutrient;
use App\Models\Pack;
use Gate;
use Symfony\Component\HttpFoundation\Response;
use Illuminate\Http\Request;

class PacksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(Gate::denies('pack_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $packs = Pack::all();

        return view('admin.packs.index', compact('packs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('pack_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.packs.create', [
            'recipes' => Recipe::get(),
            'ingredients' => Ingredient::get(),
            'nutrients' => Nutrient::get(),
        ]);
    }

    /**
     *
     */
    public function updatePackInfo (Pack $pack )
    {
        define ("INGREDIENT", 0) ;
        define ("GROUP", 1) ;

        $packNutrientsArray = array();
        $packIngredientsArray = array();

        $tmpGroupIngredientsArray = array();
        $tmpIngredientsArray = array();
        $tmpPackIngredientsArray = array();

        $packWeight = 0;
        $packWeight_real = 0;

        // pack weight = pack product * quantity - will be updated bellow
        foreach ( $pack->recipes()->get() as $recipe ) {
            $packWeight +=  $recipe->weight * $recipe->pivot->amount;
            $packWeight_real += $recipe->weight_real * $recipe->pivot->amount;
        }

        foreach ( $pack->recipes()->get() as $recipe ) {

            //dd ($value['amount']);
            $thisreciperelativeweight = ( $recipe->weight * $recipe->pivot->amount ) / $packWeight ;
            $thisreciperelativeweight_real = ( $recipe->weight_real * $recipe->pivot->amount ) / $packWeight_real  ;

            // nutrients
            $recipeNutrients = $recipe->nutrients();
            foreach ($recipeNutrients->get() as $recipeNutrient){
                if ( array_key_exists ( $recipeNutrient->id, $packNutrientsArray ) ) {
                    // nutrient * peso total / peso do produto
                    $packNutrientsArray[$recipeNutrient->id] += round ( $recipeNutrient->pivot->amount * $thisreciperelativeweight, 3, PHP_ROUND_HALF_UP)  ;
                }
                else {
                    $packNutrientsArray[$recipeNutrient->id] = round ( $recipeNutrient->pivot->amount * $thisreciperelativeweight_real, 3, PHP_ROUND_HALF_UP)  ;
                }
            }
            $pack->nutrients()->sync($this->mapNutrients($packNutrientsArray));

            // ingredients
            $recipeIngredients = $recipe->ingredients();
            foreach ($recipeIngredients->get() as $recipeIngredient){
                if ( array_key_exists ( $recipeIngredient->id, $packIngredientsArray ) ) {
                    $packIngredientsArray[$recipeIngredient->id] += round ( $recipeIngredient->pivot->amount * $thisreciperelativeweight, 3, PHP_ROUND_HALF_UP)  ;
                }
                else {
                    $packIngredientsArray[$recipeIngredient->id] = round ( $recipeIngredient->pivot->amount * $thisreciperelativeweight_real, 3, PHP_ROUND_HALF_UP)  ;
                }
            }
            $pack->ingredients()->sync($this->mapIngredients($packIngredientsArray));
        }

        //dd ($packIngredientsArray) ;
        foreach ( $packIngredientsArray as $key => $amount ) {
            // check if ingredients($key) belongs to a group
            $igroup = Ingredient::where('id', $key)->value('igroup_id');
            //var_dump ($key);
            //var_dump ($igroup[0]);
            if ( $igroup ) {
                // ingredient belong to a group
                // add $amount to amount of the group
                if ( array_key_exists ( $igroup, $tmpGroupIngredientsArray ) ) {
                    $tmpGroupIngredientsArray[$igroup] += $amount;
                } else {
                    $tmpGroupIngredientsArray[$igroup] = $amount;
                }
            } else {
                // ingredient doesn't belong to a group
                // leave $amount to ingredient
                if ( array_key_exists ( $key, $tmpIngredientsArray ) ) {
                    $tmpIngredientsArray[$key] += $amount;
                } else {
                    $tmpIngredientsArray[$key] = $amount;
                }
            }
        }

        foreach ( $tmpIngredientsArray as $key => $value ) {
            $tmpPackIngredientsArray[] = array ('type' => INGREDIENT, 'amount' => $value, 'id' => $key) ;
        }
        //dd ($tmpPackIngredientsArray);
        foreach ( $tmpGroupIngredientsArray as $key => $value ) {
            $tmpPackIngredientsArray[] = array ('type' => GROUP, 'amount' => $value, 'id' => $key) ;
        }
        //dd ($tmpPackIngredientsArray);

        // sort multidimensional array
        $amount = array();
        foreach ($tmpPackIngredientsArray as $key => $row)
        {
            $amount[$key] = $row['amount'];
        }
        array_multisort($amount, SORT_DESC, $tmpPackIngredientsArray);
        //dd ($tmpPackIngredientsArray);

        // sort for php7 - not working
//        usort($tmpGroupIngredientsArray, function ($item1, $item2) {
//            return $item2['amount'] <=> $item1['amount'];
//        });

        /**
         *
         */
        $ingredients_info = "" ;
        // sort array keeping the index association
        //dd ($packIngredientsArray);
        arsort($packIngredientsArray);
        foreach ( $tmpPackIngredientsArray as $value ) {
            if ( $value['type'] == INGREDIENT ) {
                // here we add the ingredient name
                $ingredients_info .= Ingredient::where('id', $value['id'])->value('name') . '('. $value['amount'] . '), ';
            } else {
                // here we add the group name
                $ingredients_info .= IGroup::where('id', $value['id'])->value('name') . '('. $value['amount'] . ')';

                // and all ingredients of the product belonging to that group ($value['id'])
                $ingredients_info .= ' (';
                // lets go through all ingredients for this pack
                foreach ( $packIngredientsArray as $ikey => $ivalue ) {
                        // check if the group of this ingredient is our current group. if yes add it to list
                        $i = Ingredient::where('id', $ikey)->first();
                        //echo  $i->name . "-" . $i->igroup_id . "-" . $value['id'] . "-" . $ivalue['type'] . "<br>";
                        if ( $i->igroup_id == $value['id'] ) {
                            $ingredients_info .= $i->name;
                            $ingredients_info .= ', ';
                        }
                }
                $ingredients_info .= '), ';
            }
        }
        // remove extra comma in group ingredients list and extra comma and extra space at the end (last 2 characters)
        $ingredients_info = substr(str_replace ( ", )", ")", $ingredients_info ), 0, -2) ;

        /**
         *
         */
        $nutritional_info = "";
        $nutritional_info .= "Nutrition Information (average values per 100 g): " ;
        $nutritional_info .= "Energy %d kJ/%d kcal |Fat %.1f g. " ;
        $nutritional_info .= "Of which saturates %.1f g |Carbohydrates %.1f g. " ;
        $nutritional_info .= "Of which sugars %.1f g |Protein %.1f g | Fibre %.1f g " ;
        $nutritional_info .= "Salt %.1f g" ;

        if ( count($packNutrientsArray) == 8 ) {
            $nutritional_info = sprintf ( $nutritional_info,
                                            $packNutrientsArray[2],
                                            $packNutrientsArray[1],
                                            $packNutrientsArray[3],
                                            $packNutrientsArray[4],
                                            $packNutrientsArray[5],
                                            $packNutrientsArray[6],
                                            $packNutrientsArray[7],
                                            $packNutrientsArray[8],
                                            $packNutrientsArray[9]
                                        );
        }


                                     /*
        foreach($pack->nutrients()->get() as $nutrient)
                {{ $nutrient->name }} {{ $nutrient->pivot->amount }}
        endforeach
        */

        // update
        $pack->update ( [   'weight'=> $packWeight,
                            'weight_real'=> $packWeight_real,
                            'ingredients_info' => $ingredients_info,
                            'nutritional_info' => $nutritional_info,
                            'allergenic_info' => '' ] ) ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePackRequest $request)
    {
        $data = $request->validated();

        $pack = Pack::create($data);
        $pack->recipes()->sync($this->mapRecipes($data['recipes']));

        $this->updatePackInfo ( $pack );

        if (request()->hasFile('thumbnail')) {
            $thumbnail = request()->file('thumbnail')->getClientOriginalName();
            // problem -> request id not set
            request()->file('thumbnail')->storeAs('packs/'.$pack->id.'/thumbnails', $thumbnail, '');
            $pack->update(['thumbnail'=> $thumbnail]);
        }

resources/views/admin/packs/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.pack.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.packs.store") }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.pack.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.pack.fields.name_helper') }}</span>
            </div>

            <label class="required" for="fullname">{{ trans('cruds.pack.fields.fullname') }}</label>
            <input class="form-control {{ $errors->has('fullname') ? 'is-invalid' : '' }}" type="text" name="fullname" id="fullname" value="{{ old('fullname', '') }}" required>
            @if($errors->has('fullname'))
                <div class="invalid-feedback">
                    {{ $errors->first('fullname') }}
                </div>
            @endif
            <span class="help-block">{{ trans('cruds.pack.fields.fullname_helper') }}</span>

<!--
/*
            <label class="required" for="thumbnail">{{ trans('cruds.pack.fields.thumbnail') }}</label>
            <input class="form-control {{ $errors->has('thumbnail') ? 'is-invalid' : '' }}" type="file" name="thumbnail" id="thumbnail" value="{{ old('thumbnail', '') }}" required>
            @if($errors->has('thumbnail'))
                <div class="invalid-feedback">
                    {{ $errors->first('thumbnail') }}
                </div>
            @endif
            <span class="help-block">{{ trans('cruds.pack.fields.thumbnail_helper') }}</span>
*/
-->
            <div class="form-group">
                <label class="required" for="recipes">{{ trans('cruds.pack.fields.recipes') }}</label>
                @include('admin.packs.partials.recipes')
                @if($errors->has('recipes'))
                <div class="invalid-feedback">
                    {{ $errors->first('recipes') }}
                </div>
                @endif
                <span class="help-block">{{ trans('cruds.pack.fields.recipes_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/packs/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.pack.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.packs.update", [$pack->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.pack.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $pack->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.pack.fields.name_helper') }}</span>
            </div>

            <label class="required" for="fullname">{{ trans('cruds.pack.fields.fullname') }}</label>
            <input class="form-control {{ $errors->has('fullname') ? 'is-invalid' : '' }}" type="text" name="fullname" id="fullname" value="{{ old('fullname', $pack->fullname) }}" required>
            @if($errors->has('fullname'))
                <div class="invalid-feedback">
                    {{ $errors->first('fullname') }}
                </div>
            @endif
            <span class="help-block">{{ trans('cruds.pack.fields.fullname_helper') }}</span>

            <div class="form-group">
                <label class="required" for="recipes">{{ trans('cruds.pack.fields.recipes') }}</label>

                @include('admin.packs.partials.recipes')

                @if($errors->has('recipes'))
                    <div class="invalid-feedback">
                        {{ $errors->first('recipes') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.pack.fields.recipes_helper') }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/packs/index.blade.php
@extends('layouts.admin')
@section('content')
@can('pack_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.packs.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.pack.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.pack.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Pack">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.pack.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.pack.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.pack.fields.recipes') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($packs as $key => $pack)
                        <tr data-entry-id="{{ $pack->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $pack->id ?? '' }}
                            </td>
                            <td>
                                {{ $pack->name ?? '' }}
                            </td>
                            <td>
                                @foreach($pack->recipes as $key => $item)
                                    <span class="badge badge-info">{{ $item->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                @can('pack_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.packs.show', $pack->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('pack_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.packs.edit', $pack->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('pack_delete')
                                    <form action="{{ route('admin.packs.destroy', $pack->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('pack_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.packs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Pack:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/packs/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.pack.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.packs.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.id') }}
                        </th>
                        <td>
                            {{ $pack->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.name') }}
                        </th>
                        <td>
                            {{ $pack->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.fullname') }}
                        </th>
                        <td>
                            {{ $pack->fullname }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.recipes') }}
                        </th>
                        <td>
                            <div class="label label-info">
                            @foreach($pack->recipes as $key => $recipe)
                                {{ $recipe->name }} ({{ $recipe->pivot->amount }})
                            @endforeach
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.ingredients') }}
                        </th>
                        <td>
                            <div class="label label-info">{{ trans('Ingredients')}}:
                                {{ $pack->ingredients_info }}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.pack.fields.nutrients') }}
                        </th>
                        <td>
                            <div class="label label-info">
                                {{ $pack->nutritional_info }}  <!--<button value="copy" onclick="copyToClipboard('copy_asdasd')">Copy!</button>-->
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.packs.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection