routes/web.php
<?php

Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Ingredients
    Route::delete('ingredients/destroy', 'IngredientsController@massDestroy')->name('ingredients.massDestroy');
    Route::resource('ingredients', 'IngredientsController');

    // Ingredient Groups
    Route::delete('igroups/destroy', 'IGroupsController@massDestroy')->name('igroups.massDestroy');
    Route::resource('igroups', 'IGroupsController');

    // Nutrients
    Route::delete('nutrients/destroy', 'NutrientsController@massDestroy')->name('nutrients.massDestroy');
    Route::resource('nutrients', 'NutrientsController');

    // Recipes
    Route::delete('recipes/destroy', 'RecipesController@massDestroy')->name('recipes.massDestroy');
    Route::get('recipes/{recipe}/editnutrients', 'RecipesController@editnutrients')->name('recipes.editnutrients');
    Route::get('recipes/{recipe}/editingredients', 'RecipesController@editingredients')->name('recipes.editingredients');
//    Route::post('recipes/updatenutrients', 'RecipesController@updatenutrients')->name('recipes.updatenutrients');
    Route::resource('recipes', 'RecipesController');


    // Packs
    Route::delete('packs/destroy', 'PacksController@massDestroy')->name('packs.massDestroy');
    Route::resource('packs', 'PacksController');
});

Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/Nutrient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Nutrient extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'nutrients';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/NutrientsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyNutrientRequest;
use App\Http\Requests\StoreNutrientRequest;
use App\Http\Requests\UpdateNutrientRequest;
use App\Models\Nutrient;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class NutrientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        abort_if(Gate::denies('nutrient_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $nutrients = Nutrient::all();

        return view('admin.nutrients.index', compact('nutrients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('nutrient_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.nutrients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreNutrientRequest $request)
    {
        $nutrient = Nutrient::create($request->all());

        return redirect()->route('admin.nutrients.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Nutrient  $nutrient
     * @return \Illuminate\Http\Response
     */
    public function edit(Nutrient $nutrient)
    {
        abort_if(Gate::denies('nutrient_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.nutrients.edit', compact('nutrient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Nutrient  $nutrient
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateNutrientRequest $request, Nutrient $nutrient)
    {
        $nutrient->update($request->all());

        return redirect()->route('admin.nutrients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Nutrient  $nutrient
     * @return \Illuminate\Http\Response
     */
    public function show(Nutrient $nutrient)
    {
        abort_if(Gate::denies('nutrient_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.nutrients.show', compact('nutrient'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Nutrient  $nutrient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Nutrient $nutrient)
    {
        abort_if(Gate::denies('nutrient_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $nutrient->delete();

        return back();
    }

    /**
     *
     */
    public function massDestroy(MassDestroyNutrientRequest $request)
    {
        Nutrient::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

}

resources/views/admin/nutrients/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.nutrient.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.nutrients.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.nutrient.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.nutrient.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/nutrients/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.nutrient.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.nutrients.update", [$nutrient->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="name">{{ trans('cruds.nutrient.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $nutrient->name) }}" required>
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.nutrient.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/nutrients/index.blade.php
@extends('layouts.admin')
@section('content')
@can('nutrient_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.nutrients.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.nutrient.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.nutrient.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Nutrient">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.nutrient.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.nutrient.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($nutrients as $key => $nutrient)
                        <tr data-entry-id="{{ $nutrient->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $nutrient->id ?? '' }}
                            </td>
                            <td>
                                {{ $nutrient->name ?? '' }}
                            </td>
                            <td>
                                @can('nutrient_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.nutrients.show', $nutrient->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('nutrient_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.nutrients.edit', $nutrient->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('nutrient_delete')
                                    <form action="{{ route('admin.nutrients.destroy', $nutrient->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('nutrient_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.nutrients.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Nutrient:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });

})

</script>
@endsection

resources/views/admin/nutrients/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.nutrient.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.nutrients.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.nutrient.fields.id') }}
                        </th>
                        <td>
                            {{ $nutrient->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.nutrient.fields.name') }}
                        </th>
                        <td>
                            {{ $nutrient->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.nutrients.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection